version: "2"

prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/digipolisgent/ci_config-files-and-scripts/master/php/drupal8/.csslintrc"
      path: ".csslintrc"
    - url: "https://raw.githubusercontent.com/digipolisgent/ci_config-files-and-scripts/master/php/drupal8/.eslintrc.json"
      path: ".eslintrc.json"
    - url: "https://raw.githubusercontent.com/digipolisgent/ci_config-files-and-scripts/master/php/drupal8/.eslintignore"
      path: ".eslintignore"
    - url: "https://raw.githubusercontent.com/digipolisgent/php_package_qa-php/1.x/configs/phpcs.xml"
      path: ".phpcs.xml"
    - url: "https://raw.githubusercontent.com/digipolisgent/php_package_qa-php/1.x/configs/phpmd.xml"
      path: ".phpmd.xml"

plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: ".phpcs.xml"
  phpmd:
    enabled: true
    config:
      rulesets: ".phpmd.xml"
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 55
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      # See https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
      MD024:
        enabled: false
    issue_override:
      severity: minor

exclude_patterns:
  - ".github"
  - "**/vendor/**/*"
  - "examples/"
  - "tests/"
